### ISSUE TITLE
Getting downloaded data more than actual amount.

### ISSUE THREAD

**Issue by parth1729** [feross/bittorrent-tracker#101]
I am trying to access the statistics like uploaded,downloaded and remaining from 'params'. But instead of getting the exact number of bytes downloaded, I'm getting slightly more than that. For example, if I downloaded a 108 MB file, then downloaded amount is approx. 600 KB more than that.
I need the exact statistics for my application. 
Any idea, what is happening?

**Comment by feross** [comment]
Which torrent client were you using to do the download? It might be sending the total amount of bytes that it downloaded from peers, including pieces that were invalid.

In general, you can't trust the data that is reported to the tracker, since it's all on the honor system and clients can send whatever they want.

**Comment by parth1729** [comment]
I'm using Utorrent. If its including the invalid pieces, shouldn't that be listed in "Wasted" section in Utorrrent in terms of hashfails.
And yes, you are right, we can't trust the data that is sent by the client.

**Comment by feross** [comment]
I looked through the code in `bittorrent-tracker` and I can't see any place where we're rounding up or miscalculating the data that the clients send to us. If you can find a bug in the code, then I'm happy to fix it. But I bet that it's just uTorrent sending bad data here :(
