### ISSUE TITLE
socket.io instead of simple-websocket?

### ISSUE THREAD

**Issue by harshjv** [feross/bittorrent-tracker#110]
Hello,

WebSockets are very slow to establish and this can hinder overall performance of tracker, isn't it?

So is it possible to use `socket.io` instead of `simple-websocket` for better performance?

**Comment by feross** [comment]
WebSockets are indeed unfortunately slow to establish, but we can't switch to something like socket.io because WebTorrent is a standard that is implemented by other clients, lots of them written in C++, Java, Python, etc. We don't want to make all of these implementors reverse-engineer what socket.io is doing and support that. Then the spec would be tied to whatever implementation changes socket.io happens to make in the future.

There might be other ways to make this faster, like pre-connecting to the websocket server even before `client.add` or `client.seed` is called.

**Comment by feross** [comment]
Let's move discussion to this issue: https://github.com/feross/webtorrent/issues/574
