### ISSUE TITLE
Node bittorrent tracker maximum amount of peers?

### ISSUE THREAD

**Issue by Mngz** [feross/bittorrent-tracker#88]
Hello.

I’ve been tinkering with this module for a bit and have some questions regarding large-scale performance. Some background information:

1. Let’s say my tracker would have around 100,000 peers, so a fairly large number of active connections.
2. I need to store the upload & download amount in a MySQL-database for each user, so an active connection to a database is a must, I’m guessing a caching module would be a good idea.
3. I need to be able to restrict access to the tracker, for example via a passkey, and be able to stop users from downloading torrents after they have been banned.

Would this be a situation where a Node.js backend is actually viable, compared to let’s say a pure C++ tracker backend like ”XBT”? I’m interested in a Node.js server since everyone says that Node is very scalable and I’m looking for something I can easily maintain and modify without the hassle of compiling.

How many connection would you say is the limit that a Node.js tracker could handle? I’ve read somewhere that a Node server could easily server 1million requests, does this apply to a Node tracker as well?

Thanks in advance!

**Comment by TemaSM** [comment]
Yes, Node server with Tracker functionality can be stable over 500,000 requests, just because these requests don't hard.
Tracker is just centralized server where peers discovering each others via something like ping requests and then BitTorrent protocol will do all big and hard stuff (receiving and sending packets of blocks of entire files).

So, summing up everything i said - try to use `bittorrent-tracker` module to build high-load BitTorrent Tracker and pay attention to well configured environment, such as OS, ports, RAM, gHZ and other things which will bring more stability for your app.
(advice for you: try to look on `PM2` module for Node)

Good luck with dev!

**Comment by feross** [comment]
This package is deployed in production by lots of different folks, even including BitTorrent Inc., so it's pretty stable and well-tested. That said, it's unlikely to be as scalable as something written in C or C++, like opentracker.

I would suggest trying it out and seeing if it works for you. 100,000 peers announcing every 15 minutes is just 111 requests per second, so I think it'll probably work just fine.

Bonus: If you find any obvious bottlenecks in the code, we can improve it and everyone will benefit! :+1:

Hope this answers your questions!
